### ISSUE TITLE
create database sport_platform

### ISSUE THREAD

**Issue by ArtyrGetman** [ArtyrGetman/platfor_sport#15]
Create database sport. User must see:
When he register:

login
email
password

first_name
last name
phone

Country
District
City   

When he in his work zone:

first_name   
last_name
phone
email
birthday
age
position
comment    /all  fields can be null

When hi create his group:

first_name   
last_name
phone
email
the price of abonnement
date of start abonnement
dare of end abonnement
status of paymant

**Comment by ArtyrGetman** [comment]
#table 1- register_data: 
add to fields: kinds of sports in Russ
kinds of sports in En

**Comment by intplus** [comment]
made dao model. need explanation: what is table 1(coach?), table 2(user?), table3?

**Comment by ArtyrGetman** [comment]
table1 it's a coach.  table 2 and 3 it's data of a user.  table2 use on a start work page, on another page (grop page) we use data from rable table 3, and two field from table 2.(first name and last name).
You can do multiple table or only two table( 1 table coach and 2 table user(table 2+table 3).
I do not know the best way at the moment.

**Comment by intplus** [comment]
I think that it is sufficient to use a single table "user" with a role: user(client), manager(coach), admin. Then, depending on the task to use these or other fields

**Comment by ArtyrGetman** [comment]
I agree.

**Comment by intplus** [comment]
> #table 1- register_data: 
> add to fields: kinds of sports in Russ
> kinds of sports in En
Here I can add a new table with types of sports. is it ok?

**Comment by intplus** [comment]
> Here I can add a new table with types of sports. is it ok?
done

**Comment by ArtyrGetman** [comment]
Where sql script with, which you created the table and what fields??

**Comment by intplus** [comment]
All fields is fields in model object

**Comment by ArtyrGetman** [comment]
update
