### ISSUE TITLE
create connection to the DB 

### ISSUE THREAD

**Issue by ArtyrGetman** [ArtyrGetman/platfor_sport#24]
create the connection to the DB with Hibernate, bring to the table database(clients table) data.

Table optionalities:
if the user has more than one phone number,  then this field must be the drop-down list.
Earth line must have a checkbox.

column birthday and age - it's a drop-down list, where the user can find and choose his age and date of birthday or write it himself.

In group table, fields:
 the price of abonnement
date of start abonnement
date of end  abonnement
status of payment --drop-down list with opportunity write it himself

**Comment by intplus** [comment]
done. upgrade in my branch.
You must submit data for the database in the properties file and change your password(at mvc-dispatcher-servlet.xml

**Comment by ArtyrGetman** [comment]
update
