### ISSUE TITLE
new column in the main table

### ISSUE THREAD

**Issue by ArtyrGetman** [ArtyrGetman/platfor_sport#51]
add new column field to the main table- date of making an entry
field must be filled automatically. Forman 22.08.20166

**Comment by caligula95** [comment]
Oleksandr should add some column to the table of database.

**Comment by intplus** [comment]
of course. A will make code review

**Comment by ArtyrGetman** [comment]
эту таску уже сделал, залью со следующим обновлением..

**Comment by ArtyrGetman** [comment]
есть!
