### ISSUE TITLE
Create group menu tree

### ISSUE THREAD

**Issue by ArtyrGetman** [ArtyrGetman/platfor_sport#52]
Create tree like in the picture. Trainer must to have a possibility to create category and new group in category, and behind them
![creategroup](https://cloud.githubusercontent.com/assets/15251971/19634481/3f3a2520-99c4-11e6-8bef-f78372eaecb5.png)

**Comment by intplus** [comment]
database and model ready

**Comment by ArtyrGetman** [comment]
it's good, тow we can make the implementation.

**Comment by ArtyrGetman** [comment]
done
