### ISSUE TITLE
add student from overall list

### ISSUE THREAD

**Issue by ArtyrGetman** [ArtyrGetman/platfor_sport#61]
realize add student to group or trainers group from cabinet

**Comment by ArtyrGetman** [comment]
added the invalid label 2 hours ago -- Саша зальет новую модель, можно будет делать..

**Comment by ArtyrGetman** [comment]
снимаю пометку, можно делать

**Comment by caligula95** [comment]
done

**Comment by ArtyrGetman** [comment]
закрываю, все работает.
